/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.usac.ipc.user;

import com.usac.ipc.baseDatos;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.SwingUtilities;

/**
 *
 * @author David
 */
public class Login extends javax.swing.JInternalFrame  implements Users,baseDatos {
    Usuarios users = new Usuarios();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    public void add(Usuario user){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        lblUsuario.setText("Usuario");

        lblContrasena.setText("Password");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIngresar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsuario)
                                .addComponent(txtContrasena)
                                .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblMensaje)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
//        System.out.println(usuarios.get(0).getNombre());
        // Obtener el JFrame desde el JInternalFrame
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        // Obtener la barra de menú del JFrame
        JMenuBar menuBar = frame.getJMenuBar();
        // Obtener el menú "Registro" de la barra de menú
        JMenu menuRegistro = menuBar.getMenu(1);
        JMenu menuAdmin = menuBar.getMenu(2);
        JMenu menuDeptoMuni = menuBar.getMenu(3);
        JMenu menuTarjeta = menuBar.getMenu(4);
        JMenu menuDatosFactura = menuBar.getMenu(5);
        JMenu menuCotizacion = menuBar.getMenu(6);
        for(Usuario u : usuarios){
            if(u.getCorreo().equals(txtUsuario.getText())){
                if(u.getContrasena().equals(txtContrasena.getText())){
                    switch (u.getRol()) {
                        case "admin":
                            menuRegistro.setVisible(true);
                            menuAdmin.setVisible(true);
                            menuDeptoMuni.setVisible(true);
                            
                            menuTarjeta.setVisible(false);
                            menuCotizacion.setVisible(false);
                            menuDatosFactura.setVisible(false);
                            break;
                        case "Kiosko":
                            menuRegistro.setVisible(false);
                            menuAdmin.setVisible(false);
                            menuDeptoMuni.setVisible(false);
                            menuTarjeta.setVisible(false);
                            menuCotizacion.setVisible(false);
                            menuDatosFactura.setVisible(false);
                            
                            break;
                        case "Usuario":
                            menuRegistro.setVisible(false);
                            menuAdmin.setVisible(false);
                            menuDeptoMuni.setVisible(false);
                            
                            menuTarjeta.setVisible(true);
                            menuCotizacion.setVisible(true);
                            menuDatosFactura.setVisible(true);
                            break;
                        default:
                            break;
                    }
                    this.setVisible(false);
                    //Usuario uu = Users.getUsuarioActivo();
                    //Users.modificaActivo(uu.getCorreo());
                    Users.modificaActivo(txtUsuario.getText());
                    
                }else{
                    lblMensaje.setText("Contraseña Incorrecta");
                }
                
                
            }else{
                lblMensaje.setText("Usuario No encontrado");
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
